Vaccination_System/Vaccination_System/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('patient.urls')),
    path('', include('vaccine.urls')),
    path('adminpanel/', include('adminpanel.urls')),
]



# Debug Mode

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

Vaccination_System/adminpanel/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import PatientList , PatientCreate , PatientDelete , PatientUpdate , VaccineCreate , VaccineUpdate , VaccineDelete , VaccineList , Profile , SearchList , StatusControl , PatientCard

app_name = "adminpanel"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name = "login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    # path(
    #     "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    # ),
    # path(
    #     "password_change/done/",
    #     views.PasswordChangeDoneView.as_view(),
    #     name="password_change_done",
    # ),
    # path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    # path(
    #     "password_reset/done/",
    #     views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done",
    # ),
    # path(
    #     "reset/<uidb64>/<token>/",
    #     views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm",
    # ),
    # path(
    #     "reset/done/",
    #     views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete",
    # ),
]

urlpatterns += [
    path("", PatientList.as_view() , name = "home") ,
    path("patient/create", PatientCreate.as_view() , name = "patient_create") ,
    path("patient/update/<int:pk>", PatientUpdate.as_view() , name="patient_update") ,
    path("patient/delete/<int:pk>", PatientDelete.as_view() , name="patient_delete") ,
    path("vaccine_list", VaccineList.as_view() , name = "vaccine_list") ,\
    path("vaccine/create", VaccineCreate.as_view() , name = "vaccine_create") ,
    path("vaccine/update/<int:pk>", VaccineUpdate.as_view() , name="vaccine_update") ,
    path("vaccine/delete/<int:pk>", VaccineDelete.as_view() , name="vaccine_delete") ,
    path("profile/", Profile.as_view() , name="profile"),
    path('search/' , SearchList.as_view() , name="search"),
    path('status_control/' , StatusControl , name="status_control"),
    path('preview/<int:pk>' , PatientCard.as_view() , name='preview'),
]

Vaccination_System/patient/urls.py
from django.urls import path , include
from .views import PatientList

app_name = 'patient'
urlpatterns = [
    path('patient/' , PatientList.as_view() , name = 'patients'),
]

Vaccination_System/vaccine/urls.py
from django.urls import path 
from .views import VaccineList , CategoryList , VaccineDetail

app_name = 'vaccine'
urlpatterns = [
    path('' , VaccineList.as_view() , name = 'vaccines'),
    path('category/<slug:slug>' , CategoryList.as_view() , name='category'),
    path('vaccine/<slug:slug>' , VaccineDetail.as_view() , name='details'),
]   
    

Vaccination_System/vaccine/models.py
from django.db import models
from django.utils.html import format_html
from django.urls import reverse

#My_Managers

class VaccineManager(models.Manager):
    def available (self):
        return self.filter(availablity = True)


class CategoryManager(models.Manager):
    def active (self):
        return self.filter(status = True)

# Vaccine Models

class Category (models.Model):
    title = models.CharField(max_length=200 , verbose_name ='عنوان دسته بندی')
    slug = models.SlugField(max_length=100 , unique=True , verbose_name ='آدرس دسته یندی')
    parent = models.ForeignKey('self' , default = None , null = True , blank = True , on_delete = models.SET_NULL , related_name = 'children' , verbose_name = 'زیر دسته')
    status = models.BooleanField(verbose_name ='انتشار داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشن دسته بندی') 
   
    class Meta :
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['parent__id' ,'position']
    
    def __str__(self):
        return self.title

    objects = CategoryManager()



class Vaccine(models.Model):
    name = models.CharField(max_length = 100 , verbose_name = 'نام واکسن')
    slug = models.SlugField(max_length = 100 , unique = True , verbose_name = 'نشانی واکسن')
    country = models.CharField(max_length = 100 , verbose_name = 'کشور تولید کننده')
    count = models.IntegerField(verbose_name = 'تعداد دوز های وارد شده')
    description = models.TextField(null = True , blank = True , verbose_name ='توضیحات واکسن')
    picture = models.ImageField(upload_to = "images" , default = 'images/vaccine_def.jpg' , verbose_name ='تصویر واکسن')
    availablity = models.BooleanField(default = True , verbose_name ='وضعیت موجودی واکسن')
    category = models.ManyToManyField(Category , related_name="vaccines" , verbose_name='دسته بندی')
    usage = models.IntegerField(null = True , blank = True , verbose_name = 'تعداد دوز های موجود ')


    def is_available (self):
        if self.count == '0':
            return self.availablity == False
        else:      
            return self.availablity == True
    is_available.boolean = True
    is_available.short_description = 'وضعیت موجودی واکسن'

    class Meta :
        verbose_name = 'واکسن'
        verbose_name_plural = 'واکسن ها'
        ordering = ['count' ,'name']
        
    def __str__(self):
        return self.name 

    def picture_tag(self):
        return format_html("<img width=95 height=80 style='border-radius: 8px;' src='{}'>".format(self.picture.url))
    picture_tag.short_description = "عکس"

    def Category_to_str(self):
        return " , ".join([category.title for category in self.category.active()])
    Category_to_str.short_description = "دسته بندی"

    def get_absolute_url(self):
        return reverse('adminpanel:vaccine_list')

    objects = VaccineManager()

Vaccination_System/vaccine/views.py
from django.views.generic import ListView , DetailView
from .models import Vaccine , Category
from django.shortcuts import get_object_or_404

# Vaccine Views

class VaccineList(ListView):

    queryset = Vaccine.objects.available()

    
class CategoryList(ListView):

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active() , slug = slug)
        return category.vaccines.available()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context



class VaccineDetail(DetailView):

    def get_object(self):
        slug = self.kwargs.get('slug')
        vaccine = get_object_or_404(Vaccine.objects.available() , slug = slug)

        return vaccine

Vaccination_System/templates/vaccine/base.html
{% load static %}

{% load base_tags %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Vaccination-System | {% block meta %} {% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="{% static 'patient/favicon.ico' %}">

	<link href="https://fonts.googleapis.com/css?family=Raleway:200,300,400,700" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'patient/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'patient/css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'patient/css/bootstrap.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'patient/css/flexslider.css' %}">
	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'patient/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'patient/css/owl.theme.default.min.css' %}">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'patient/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'patient/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>
	
	
	<div id="fh5co-page">
	<header id="fh5co-header" role="banner">
		<div class="container">
			<div class="header-inner">
				<h1><a href="{% url 'vaccine:vaccines' %}">{% Web_Title %}</a></h1>
				<nav role="navigation">
					{% Category_Navbar %}
				</nav>
			</div>
		</div>
	</header>
	
	<div class="container">
		
	</div>
	
	<!-- Main Content -->
	{% block main %}
	
	{% endblock %}
	
	
	<footer id="fh5co-footer" role="contentinfo">
	
		<div class="container">
			<div class="col-md-3 col-sm-12 col-sm-push-0 col-xs-12 col-xs-push-0">
				<h3>آدرس</h3>
				<p>کرمان، چهار راه شفا ،مرکز بهداشت</p>
				<p><a href="https://instagram.com/tpook.official?igshid=YmMyMTA2M2Y=" class="btn btn-primary btn-outline with-arrow btn-sm">تماس با ما </a></p>
			</div>
			<div class="col-md-6 col-md-push-1 col-sm-12 col-sm-push-0 col-xs-12 col-xs-push-0">
				<h3>پیوندهای مرتبط </h3>
				<ul class="float">
					<li><a href="https://www.kmu.ac.ir/fa">دانشگاه علوم پزشکی استان کرمان</a></li>
					<li><a href="https://behdasht.gov.ir/">وزارت بهداشت</a></li>
					<li><a href="https://kermanhc.kmu.ac.ir/fa">مراکـــز بهداشت استان کرمان</a></li>
				</ul>
				<ul class="float">
					<li><a href="https://www.kmu.ac.ir/fa">دانشگاه علوم پزشکی استان کرمان</a></li>
					<li><a href="https://behdasht.gov.ir/">وزارت بهداشت</a></li>
					<li><a href="https://kermanhc.kmu.ac.ir/fa">مراکـــز بهداشت استان کرمان</a></li>
				</ul>

			</div>
			<div class="col-md-12 fh5co-copyright text-center">
				<p>Copyright 2018-2023 &copy; - است <a href="https://instagram.com/tpook.official?igshid=YmMyMTA2M2Y=">TPOOK</a>   کلیه حقوق این وب‌سایت متعلق به گروه </p>	
			</div>
		</div>
	</footer>
	</div>
	
	
	<!-- jQuery -->
	<script src="{% static 'patient/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'patient/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'patient/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'patient/js/jquery.waypoints.min.js' %}"></script>
	<!-- Owl Carousel -->
	<script src="{% static 'patient/js/owl.carousel.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'patient/js/jquery.flexslider-min.js' %}"></script>

	<!-- MAIN JS -->
	<script src="{% static 'patient/js/main.js' %}"></script>

	</body>
</html>

Vaccination_System/templates/vaccine/vaccine_detail.html
{% extends 'vaccine/base.html' %}

{% block meta %} {{object.name}} {% endblock %}

{% block main %}

    <aside id="fh5co-hero" class="js-fullheight">
        <div class="flexslider js-fullheight">
            <ul class="slides">
            <li style='background-image: url({{object.picture.url}});'>
                <div class="overlay-gradient"></div>
                <div class="container">
                    <div class="col-md-10 col-md-offset-1 text-center js-fullheight slider-text">
                        <div class="slider-text-inner">
                            <h2 style="color: black;">{{object.name}}</h2>>
                        </div>
                    </div>
                </div>
            </li>
    </aside> 

    <div id="fh5co-services-section">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 text-center fh5co-heading animate-box">
					<h2>{{object.name}}</h2>
					<p>{{object.description}}</p>
				</div>
            </div>
	    </div>
    </div>

{% endblock %}

Vaccination_System/templates/vaccine/vaccine_list.html
{% extends 'vaccine/base.html' %}

{% load static %}

{% block meta %} {% if category.title %} {{category.title}} {% else %} Vaccines {% endif %} {% endblock %}

{% block main %}

    <aside id="fh5co-hero" class="js-fullheight">
        <div class="flexslider js-fullheight">
            <ul class="slides">
                <li style='background-image: url("{% static "patient/images/S1.jpg" %}");'>
                    <div class="overlay-gradient"></div>
                    <div class="container">
                        <div class="col-md-10 col-md-offset-1 text-center js-fullheight slider-text">
                            <div class="slider-text-inner">
                                <h2 style="color: black;">استعلام واکسیناسیون کرونا</h2>
                                <p><a href="{% url 'adminpanel:home' %}" class="btn btn-primary btn-lg">ورود به سامانه</a></p>
                            </div>
                        </div>
                    </div>
                </li>
                <li style='background-image: url("{% static "patient/images/S2.jpeg" %}");'>
                    <div class="container">
                        <div class="col-md-10 col-md-offset-1 text-center js-fullheight slider-text">
                            <div class="slider-text-inner">
                                <h2 style="color: black;">ثبت نام واکسیناسیون کرونا</h2>
                                <p><a href="{% url 'adminpanel:home' %}" class="btn btn-primary btn-lg">ورود به سامانه</a></p>
                            </div>
                        </div>
                    </div>
                </li>
                <li style='background-image: url("{% static "patient/images/S3.jpg" %}");'>
                    <div class="container">
                        <div class="col-md-10 col-md-offset-1 text-center js-fullheight slider-text">
                            <div class="slider-text-inner">
                                <h2 style="color: black;">لیــست مراکـــز واکسینــاسیــون</h2>
                                <p><a href="#" class="btn btn-primary btn-lg">مراکـــز واکسیناسیون</a></p>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </aside>    

    <div id="fh5co-work-section" class="fh5co-light-grey-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center fh5co-heading animate-box">
                    <h2>{% if category.title %} {{category.title}} {% else %} واکسن ها {% endif %}</h2>
                </div>
            </div>
            <div class="row">
                {% for vaccine in object_list %}
                    <div class="col-md-4 animate-box">
                        <a href="{% url 'vaccine:details' vaccine.slug %}" class="item-grid text-center">
                            <div class="image" style="background-image: url({{vaccine.picture.url}})"></div>
                            <div class="v-align">
                                <div class="v-align-middle">
                                    <h3 class="title">{{vaccine.name}}</h3>
                                    <h5 class="category">{{ vaccine.country }}</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                {% empty %}
                    <h4 style="padding: 8px ; margin-bottom: 45px; text-align: center;">متاسقانه محتوایی برای نمایش در این مورد وجود ندارد.</h4>
                {% endfor %}
               
            </div>
        </div>
    </div>

{% endblock %}